


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 388)
        MainWindow.setStyleSheet("background-color: rgb(188, 202, 167);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_sete = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sete.setGeometry(QtCore.QRect(480, 120, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_sete.setFont(font)
        self.botao_sete.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_sete.setObjectName("botao_sete")
        self.botao_somar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_somar.setGeometry(QtCore.QRect(330, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_somar.setFont(font)
        self.botao_somar.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_somar.setObjectName("botao_somar")
        self.botao_multiplicar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_multiplicar.setGeometry(QtCore.QRect(250, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_multiplicar.setFont(font)
        self.botao_multiplicar.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_multiplicar.setObjectName("botao_multiplicar")
        self.botao_subtrair = QtWidgets.QPushButton(self.centralwidget)
        self.botao_subtrair.setGeometry(QtCore.QRect(170, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_subtrair.setFont(font)
        self.botao_subtrair.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_subtrair.setObjectName("botao_subtrair")
        self.botao_dividir = QtWidgets.QPushButton(self.centralwidget)
        self.botao_dividir.setGeometry(QtCore.QRect(90, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_dividir.setFont(font)
        self.botao_dividir.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_dividir.setObjectName("botao_dividir")
        self.botao_oito = QtWidgets.QPushButton(self.centralwidget)
        self.botao_oito.setGeometry(QtCore.QRect(560, 120, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_oito.setFont(font)
        self.botao_oito.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_oito.setObjectName("botao_oito")
        self.botao_nove = QtWidgets.QPushButton(self.centralwidget)
        self.botao_nove.setGeometry(QtCore.QRect(640, 120, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_nove.setFont(font)
        self.botao_nove.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_nove.setObjectName("botao_nove")
        self.botao_quatro = QtWidgets.QPushButton(self.centralwidget)
        self.botao_quatro.setGeometry(QtCore.QRect(480, 170, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_quatro.setFont(font)
        self.botao_quatro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_quatro.setObjectName("botao_quatro")
        self.botao_seis = QtWidgets.QPushButton(self.centralwidget)
        self.botao_seis.setGeometry(QtCore.QRect(640, 170, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_seis.setFont(font)
        self.botao_seis.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_seis.setObjectName("botao_seis")
        self.botao_cinco = QtWidgets.QPushButton(self.centralwidget)
        self.botao_cinco.setGeometry(QtCore.QRect(560, 170, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_cinco.setFont(font)
        self.botao_cinco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_cinco.setObjectName("botao_cinco")
        self.botao_um = QtWidgets.QPushButton(self.centralwidget)
        self.botao_um.setGeometry(QtCore.QRect(480, 220, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_um.setFont(font)
        self.botao_um.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_um.setObjectName("botao_um")
        self.botao_tres = QtWidgets.QPushButton(self.centralwidget)
        self.botao_tres.setGeometry(QtCore.QRect(640, 220, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_tres.setFont(font)
        self.botao_tres.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_tres.setObjectName("botao_tres")
        self.botao_dois = QtWidgets.QPushButton(self.centralwidget)
        self.botao_dois.setGeometry(QtCore.QRect(560, 220, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_dois.setFont(font)
        self.botao_dois.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_dois.setObjectName("botao_dois")
        self.botao_enter = QtWidgets.QPushButton(self.centralwidget)
        self.botao_enter.setGeometry(QtCore.QRect(444, 270, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_enter.setFont(font)
        self.botao_enter.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_enter.setObjectName("botao_enter")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(640, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(560, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton_24.setObjectName("pushButton_24")
        self.botao_limpar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_limpar.setGeometry(QtCore.QRect(10, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_limpar.setFont(font)
        self.botao_limpar.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_limpar.setObjectName("botao_limpar")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 320, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("background-color: rgb(255, 75, 43);")
        self.pushButton_26.setObjectName("pushButton_26")
        self.botao_percentual = QtWidgets.QPushButton(self.centralwidget)
        self.botao_percentual.setGeometry(QtCore.QRect(90, 210, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_percentual.setFont(font)
        self.botao_percentual.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_percentual.setObjectName("botao_percentual")
        self.outputLabel = QtWidgets.QLCDNumber(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(0, 10, 731, 81))
        self.outputLabel.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.outputLabel.setObjectName("outputLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.botao_sete.setText(_translate("MainWindow", "7"))
        self.botao_somar.setText(_translate("MainWindow", "+"))
        self.botao_multiplicar.setText(_translate("MainWindow", "X"))
        self.botao_subtrair.setText(_translate("MainWindow", "-"))
        self.botao_dividir.setText(_translate("MainWindow", "/"))
        self.botao_oito.setText(_translate("MainWindow", "8"))
        self.botao_nove.setText(_translate("MainWindow", "9"))
        self.botao_quatro.setText(_translate("MainWindow", "4"))
        self.botao_seis.setText(_translate("MainWindow", "6"))
        self.botao_cinco.setText(_translate("MainWindow", "5"))
        self.botao_um.setText(_translate("MainWindow", "1"))
        self.botao_tres.setText(_translate("MainWindow", "3"))
        self.botao_dois.setText(_translate("MainWindow", "2"))
        self.botao_enter.setText(_translate("MainWindow", "ENTER"))
        self.pushButton_23.setText(_translate("MainWindow", "."))
        self.pushButton_24.setText(_translate("MainWindow", "0"))
        self.botao_limpar.setText(_translate("MainWindow", "C"))
        self.pushButton_26.setText(_translate("MainWindow", "ON"))
        self.botao_percentual.setText(_translate("MainWindow", "%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
