

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 388)
        MainWindow.setStyleSheet("background-color: rgb(188, 202, 167);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(0, 0, 730, 101))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.outputLabel.setFont(font)
        self.outputLabel.setStyleSheet("background-color: rgb(0, 2, 167")
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputLabel.setLineWidth(3)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.botao_sete = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("7"))
        self.botao_sete.setGeometry(QtCore.QRect(480, 120, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_sete.setFont(font)
        self.botao_sete.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_sete.setObjectName("botao_sete")
        self.botao_somar = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("+"))
        self.botao_somar.setGeometry(QtCore.QRect(330, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_somar.setFont(font)
        self.botao_somar.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_somar.setObjectName("botao_somar")
        self.botao_multiplicar = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("*"))
        self.botao_multiplicar.setGeometry(QtCore.QRect(250, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_multiplicar.setFont(font)
        self.botao_multiplicar.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_multiplicar.setObjectName("botao_multiplicar")
        self.botao_subtrair = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("-"))
        self.botao_subtrair.setGeometry(QtCore.QRect(170, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_subtrair.setFont(font)
        self.botao_subtrair.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_subtrair.setObjectName("botao_subtrair")
        self.botao_dividir = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("/"))
        self.botao_dividir.setGeometry(QtCore.QRect(90, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_dividir.setFont(font)
        self.botao_dividir.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_dividir.setObjectName("botao_dividir")
        self.botao_oito = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("8"))
        self.botao_oito.setGeometry(QtCore.QRect(560, 120, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_oito.setFont(font)
        self.botao_oito.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_oito.setObjectName("botao_oito")
        self.botao_nove = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("9"))
        self.botao_nove.setGeometry(QtCore.QRect(640, 120, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_nove.setFont(font)
        self.botao_nove.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_nove.setObjectName("botao_nove")
        self.botao_quatro = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("4"))
        self.botao_quatro.setGeometry(QtCore.QRect(480, 170, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_quatro.setFont(font)
        self.botao_quatro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_quatro.setObjectName("botao_quatro")
        self.botao_seis = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("6"))
        self.botao_seis.setGeometry(QtCore.QRect(640, 170, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_seis.setFont(font)
        self.botao_seis.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_seis.setObjectName("botao_seis")
        self.botao_cinco = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("5"))
        self.botao_cinco.setGeometry(QtCore.QRect(560, 170, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_cinco.setFont(font)
        self.botao_cinco.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_cinco.setObjectName("botao_cinco")
        self.botao_um = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("1"))
        self.botao_um.setGeometry(QtCore.QRect(480, 220, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_um.setFont(font)
        self.botao_um.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_um.setObjectName("botao_um")
        self.botao_tres = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("3"))
        self.botao_tres.setGeometry(QtCore.QRect(640, 220, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_tres.setFont(font)
        self.botao_tres.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_tres.setObjectName("botao_tres")
        self.botao_dois = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("2"))
        self.botao_dois.setGeometry(QtCore.QRect(560, 220, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_dois.setFont(font)
        self.botao_dois.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_dois.setObjectName("botao_dois")
        self.botao_enter = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.enter_it())
        self.botao_enter.setGeometry(QtCore.QRect(444, 270, 111, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_enter.setFont(font)
        self.botao_enter.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_enter.setObjectName("botao_enter")
        self.botao_ponto = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.dot_it ())
        self.botao_ponto.setGeometry(QtCore.QRect(640, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_ponto.setFont(font)
        self.botao_ponto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_ponto.setObjectName("pushButton_23")
        self.botao_zero = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("0"))
        self.botao_zero.setGeometry(QtCore.QRect(560, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_zero.setFont(font)
        self.botao_zero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.botao_zero.setObjectName("pushButton_24")
        self.botao_limpar = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("C"))
        self.botao_limpar.setGeometry(QtCore.QRect(10, 270, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_limpar.setFont(font)
        self.botao_limpar.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_limpar.setObjectName("botao_limpar")
        self.botao_ligar = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.press_it("ON"))
        self.botao_ligar.setGeometry(QtCore.QRect(10, 320, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_ligar.setFont(font)
        self.botao_ligar.setStyleSheet("background-color: rgb(255, 75, 43);")
        self.botao_ligar.setObjectName("pushButton_26")
        self.botao_percentual = QtWidgets.QPushButton(self.centralwidget,clicked= lambda: self.press_it("%"))
        self.botao_percentual.setGeometry(QtCore.QRect(90, 210, 75, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.botao_percentual.setFont(font)
        self.botao_percentual.setStyleSheet("background-color: rgb(94, 117, 121);")
        self.botao_percentual.setObjectName("botao_percentual")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculadora"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.botao_sete.setText(_translate("MainWindow", "7"))
        self.botao_somar.setText(_translate("MainWindow", "+"))
        self.botao_multiplicar.setText(_translate("MainWindow", "X"))
        self.botao_subtrair.setText(_translate("MainWindow", "-"))
        self.botao_dividir.setText(_translate("MainWindow", "/"))
        self.botao_oito.setText(_translate("MainWindow", "8"))
        self.botao_nove.setText(_translate("MainWindow", "9"))
        self.botao_quatro.setText(_translate("MainWindow", "4"))
        self.botao_seis.setText(_translate("MainWindow", "6"))
        self.botao_cinco.setText(_translate("MainWindow", "5"))
        self.botao_um.setText(_translate("MainWindow", "1"))
        self.botao_tres.setText(_translate("MainWindow", "3"))
        self.botao_dois.setText(_translate("MainWindow", "2"))
        self.botao_enter.setText(_translate("MainWindow", "ENTER"))
        self.botao_ponto.setText(_translate("MainWindow", "."))
        self.botao_zero.setText(_translate("MainWindow", "0"))
        self.botao_limpar.setText(_translate("MainWindow", "C"))
        self.botao_ligar.setText(_translate("MainWindow", "ON"))
        self.botao_percentual.setText(_translate("MainWindow", "%"))

    def dot_it(self):
        screen = self.outputLabel.text()

        if screen[-1] == ".":
            pass
        else:
            self.outputLabel.setText(f'{screen}.')

    def press_it(self, pressed):
        if pressed =="C":
            self.outputLabel.setText('0')
        else:
            if self.outputLabel.text() =="0":
                self.outputLabel.setText("")
            self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

    def enter_it(self):
        screen = self.outputLabel.text()

        try:
            resposta = eval(screen)
            self.outputLabel.setText(str(resposta))
        except:
            self.outputLabel.setText('ERROR 404')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
